- name: Ping to server
  ping:

- name: Install tools
  become: yes
  apt: deb='{{ item }}'
  with_items:
    - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

- name: Install VSCode
  become: yes
  snap:
    classic: yes
    name:
      - code
      - pycharm-community
      - postman
      - slack