# Install NVM
- name: Download NVM script
  become: yes
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/master/install.sh
    dest: ../../storage
    mode: 0755

- name: Install NVM
  script: ../../storage/install.sh

- name: Install latest LTS Node
  shell: source /home/{{ username }}/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash